#!/bin/bash

# Folder tujuan
OUT_DIR="d:/CDP-Proyek/frontend/src/assets/icons"
BASE_URL="https://raw.githubusercontent.com/lucide-icons/lucide/main/icons"

# Daftar icon (name -> kebab-case filename)
declare -A ICONS=(
  ["Activity"]="activity"
  ["ArrowDown"]="arrow-down"
  ["ArrowLeft"]="arrow-left"
  ["ArrowRight"]="arrow-right"
  ["BatteryFull"]="battery-full"
  ["Check"]="check"
  ["ChevronDownIcon"]="chevron-down"
  ["ChevronLeft"]="chevron-left"
  ["ChevronRight"]="chevron-right"
  ["ChevronUpIcon"]="chevron-up"
  ["CircleCheckIcon"]="circle-check"
  ["Clock"]="clock"
  ["Cloud"]="cloud"
  ["CloudLightning"]="cloud-lightning"
  ["CloudOff"]="cloud-off"
  ["CloudRain"]="cloud-rain"
  ["CloudRainWind"]="cloud-rain-wind"
  ["CloudSun"]="cloud-sun"
  ["Cpu"]="cpu"
  ["Download"]="download"
  ["Droplet"]="droplet"
  ["Droplets"]="droplets"
  ["Eye"]="eye"
  ["EyeOff"]="eye-off"
  ["Gauge"]="gauge"
  ["HelpCircle"]="help-circle"
  ["History"]="history"
  ["Home"]="home"
  ["Info"]="info"
  ["KeyRound"]="key-round"
  ["LayoutDashboard"]="layout-dashboard"
  ["LineChart"]="line-chart"
  ["Loader2"]="loader-2"
  ["LogIn"]="log-in"
  ["LogOut"]="log-out"
  ["MapPin"]="map-pin"
  ["Menu"]="menu"
  ["Minus"]="minus"
  ["MoreVertical"]="more-vertical"
  ["OctagonXIcon"]="octagon-x"
  ["PanelLeftIcon"]="panel-left"
  ["Pencil"]="pencil"
  ["Plus"]="plus"
  ["Radio"]="radio"
  ["RadioTower"]="radio-tower"
  ["Search"]="search"
  ["Settings"]="settings"
  ["Signal"]="signal"
  ["Sprout"]="sprout"
  ["Star"]="star"
  ["Sun"]="sun"
  ["Thermometer"]="thermometer"
  ["ThermometerSun"]="thermometer-sun"
  ["Timer"]="timer"
  ["TriangleAlert"]="triangle-alert"
  ["TriangleAlertIcon"]="triangle-alert"
  ["UserCog"]="user-cog"
  ["UserPlus"]="user-plus"
  ["Waves"]="waves"
  ["Wifi"]="wifi"
  ["WifiOff"]="wifi-off"
  ["X"]="x"
  ["XIcon"]="x"
  ["Zap"]="zap"
)

# Download semua icon
for name in "${!ICONS[@]}"; do
  filename="${ICONS[$name]}.svg"
  url="${BASE_URL}/${filename}"
  echo "Downloading: $name -> $filename"
  curl -sL "$url" -o "${OUT_DIR}/${filename}"
done

echo ""
echo "Download complete. Checking files..."
ls -la "$OUT_DIR" | head -20
echo "Total files: $(ls -1 "$OUT_DIR" | wc -l)"
